const statuses = {
  DRAFT: 'DRAFT',
  CANCELLED: 'CANCELLED',
  APPROVED: 'APPROVED',
  CLOSED: 'CLOSED',
  EXPIRED: 'EXPIRED',
  ACTIVE: 'ACTIVE',
  IDLE: 'IDLE',
  SENT: 'SENT',
  PARTIAL: 'PARTIAL',
  PAID: 'PAID',
  PENDING_REVIEW: 'PENDING_REVIEW',
  REJECTED: 'REJECTED',
  SUSPENDED: 'SUSPENDED',
  DELETED: 'DELETED',
}

module.exports = statuses
